#!/bin/sh

. "$(dirname $0)"/common

PKG_CONF="$ETC_PATH/config"

echo "HOSTNAME=$pkgwizard_hostname" > $PKG_CONF
echo "EXTERNAL_URL=http://$pkgwizard_hostname:$pkgwizard_http_port" >> $PKG_CONF
echo "GITLAB_SHELL_SSH_PORT=$pkgwizard_ssh_port" >> $PKG_CONF
echo "GITLAB_HTTP_PORT=$pkgwizard_http_port" >> $PKG_CONF
echo "GITLAB_HTTPS_PORT=$pkgwizard_https_port" >> $PKG_CONF

if [ -f "$SYNOPKG_PKGDEST/ui/config" ]; then
    sed -i -e "s|__PORT__|$pkgwizard_http_port|g" "$SYNOPKG_PKGDEST/ui/config"
fi

# synowebapi --exec api=SYNO.Docker.Container.Profile version=1 method=export name="synology-gitlab-ce" 2> /dev/null | tail -n +4 | jq --slurp '.[0]' > "$ETC_PATH/aaaaaaa" 2> /dev/null
sudo synowebapi --exec api=SYNO.Docker.Container.Profile version=1 method=export name="synology-gitlab-ce" > "$ETC_PATH/aaaaaaa"

exit 0
