#!/bin/sh
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

### This script will be executed ONLY at package upgraded.
### Actions after package upgraded.
### ex. restore user settings.

if [ -f "$SYNOPKG_TEMP_UPGRADE_FOLDER/ui.config" ]; then
  cp -f "$SYNOPKG_TEMP_UPGRADE_FOLDER/ui.config" "$SYNOPKG_PKGDEST/ui/config"
fi

exit 0
