#!/bin/sh
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

### This script will be executed when package uninstalled and upgraded.
### Actions before package uninstalled
### ex. backup package data.

. "$(dirname $0)"/common

PKG_CONF="$ETC_PATH/config"

if [ -f "$PKG_CONF" ]; then
  rm -f "$PKG_CONF"
fi

exit 0
