#!/bin/sh
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

### This script will execute ONLY when package upgraded.
### Actions before package upgraded.
### ex. backup user settings for package upgrade.

exit 0
