#!/bin/bash

version="16.3.0"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2

version="16.3.9"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2

version="16.7.10"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2

version="16.11.10"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2

version="17.1.8"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2

version="17.3.7"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2

version="17.5.5"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2

version="17.8.7"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2

version="17.11.3"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2

version="18.0.1"; \
./build.sh --version="$version"-ce.0 --dsm=6.0 && \
./build.sh --version="$version"-ce.0 --dsm=6.2 && \
./build.sh --version="$version"-ce.0 --dsm=7.0 && \
./build.sh --version="$version"-ce.0 --dsm=7.1 && \
./build.sh --version="$version"-ce.0 --dsm=7.2